name: YasLifeCaseStudy_0_63_2 Test and Build
on:
    push:
        branches:
            - master
#         paths: 
#             - YasLifeCaseStudy_0_63_2/**
defaults:
    run:
        working-directory: ./YasLifeCaseStudy_0_63_2
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create env file
#               working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                  touch .env
                  echo FIXER_KEY=${{ secrets.FIXER_KEY }} > .env
                  echo ${{ env.GITHUB_WORKSPACE }}
            - name: Cache or Restore dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('${{ env.GITHUB_WORKSPACE }}/YasLifeCaseStudy_0_63_2/yarn.lock') }}
            - name: Install dependencies and test
#               working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                yarn --frozen-lockfile
                yarn pre-push-check
    build-android:
        name: Build Android release APKs
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create env file
#               working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                 touch .env
                 echo FIXER_KEY=${{ secrets.FIXER_KEY }} > .env
            - name: Restore cached dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.cache/yarn
                  key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('${{ env.GITHUB_WORKSPACE }}/YasLifeCaseStudy_0_63_2/yarn.lock') }}
            - name: Install dependencies
#               working-directory: ./YasLifeCaseStudy_0_63_2
              run: yarn --frozen-lockfile
            - name: Build Android Release
#               working-directory: ./YasLifeCaseStudy_0_63_2/android
              run: |
                cd android
                ./gradlew assembleRelease
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: apks
                  path: ./YasLifeCaseStudy_0_63_2/android/app/build/outputs/apk/release/
