name: YasLifeCaseStudy_0_63_2 Test and Build
on:
    push:
        branches:
            - master
jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create env file
              working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                  touch .env
                  echo FIXER_KEY=${{ secrets.FIXER_KEY }} > .env
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-node-modules-cache-${{ hashFiles('yarn.lock') }}
            - name: Install dependencies and test
              working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                yarn 
                yarn test
    build-android:
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Create env file
              working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                 touch .env
                 echo FIXER_KEY=${{ secrets.FIXER_KEY }} > .env
            - name: Install dependencies
              working-directory: ./YasLifeCaseStudy_0_63_2
              run: npm install
            - name: Build Android Release
              working-directory: ./YasLifeCaseStudy_0_63_2/android
              run: ./gradlew assembleRelease
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: apks
                  path: ./YasLifeCaseStudy_0_63_2/android/app/build/outputs/apk/release/
