name: react-native-android-build-apk
on:
    push:
        branches:
            - master
jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              working-directory: ./YasLifeCaseStudy_0_63_2
              run: |
                npm install 
                'echo "$FIXER_KEY=${{ secrets.FIXER_KEY }}" > .env'
                npm test
    build-android:
        needs: install-and-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: cd YasLifeCaseStudy_0_63_2 && npm install
              env:
                  FIXER_KEY: ${{ secrets.FIXER_KEY }}
            - name: Build Android Release
              run: cd YasLifeCaseStudy_0_63_2/android && ./gradlew assembleRelease
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: apks
                  path: YasLifeCaseStudy_0_63_2/android/app/build/outputs/apk/release/
